behaviors:
  WormSimple:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: linear
      batch_size: 1000
      buffer_size: 1000000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 30.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 30.0
    network_settings:
      normalize: true
      hidden_units: 1024
      num_layers: 3
      vis_encode_type: simple
      memory:
        sequence_length: 1000
        memory_size: 1024
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        strength: 0.1
        gamma: 0.995
        network_settings:
          hidden_units: 1024
          learning_rate: 0.0001
    keep_checkpoints: 100
    checkpoint_interval: 10000
    max_steps: 1000000
    time_horizon: 1000
    summary_freq: 10000
